### ISSUE TITLE
Format of data list

### ISSUE THREAD

**Issue by redhat12345** [deepinsight/transfer-mxnet#1]
Could you please tell about format the list of dataset.

Is it like the following:

/home/user/office/amazon/images/bottle/001.jpg   0
/home/user/office/amazon/images/bottle/002.jpg   0
/home/user/office/amazon/images/bottle/002.jpg   0
-----------------------------------------------------------------
/home/user/office/amazon/images/bag/001.jpg   1
/home/user/office/amazon/images/bag/002.jpg   1
/home/user/office/amazon/images/bag/002.jpg   1

**Comment by nttstar** [comment]
It should follow the mxnet lst format, each line is  <item_idx>\t<label_id>\t<image_path>.
for example:

0 0 /home/user/office/amazon/images/bottle/001.jpg
1 0 /home/user/office/amazon/images/bottle/002.jpg
...
101 30 /home/user/office/amazon/images/xxx/001.jpg
102 30 /home/user/office/amazon/images/xxx/002.jpg

**Comment by redhat12345** [comment]
Thank you so much for your reply.  If the total images are 795 for an example.

so the item_idx would be

0 to 794. Am I right ?

**Comment by nttstar** [comment]
Yes right.

**Comment by redhat12345** [comment]
Thank you so much for your kind reply. Is there any script to create image list from folder with subfolder for mxnet?

**Comment by nttstar** [comment]
No, you should write one according to your own requirement.
